# Generated by Django 4.2.1 on 2023-05-15 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dep', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='table_data.department')),
            ],
        ),
    ]
