# Generated by Django 4.2.1 on 2023-05-16 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_data', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table_data.department'),
        ),
    ]
