# Generated by Django 4.2.1 on 2023-05-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_data', '0003_alter_employee_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
