# Generated by Django 4.2.1 on 2023-05-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_data', '0007_employee_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
