# Generated by Django 4.2.1 on 2023-05-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_data', '0010_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('books', models.ManyToManyField(to='table_data.book')),
            ],
        ),
    ]
