# Generated by Django 4.2.1 on 2023-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_data', '0011_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='books',
            field=models.ManyToManyField(related_name='store_list', to='table_data.book'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('publications', models.ManyToManyField(to='table_data.publication')),
            ],
        ),
    ]
