# Generated by Django 4.2.1 on 2023-05-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_data', '0014_publication_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
