# Generated by Django 4.2.1 on 2023-05-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_data', '0020_publication_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='dep_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
