# Generated by Django 4.2.1 on 2023-05-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_data', '0021_alter_employee_options_employee_dep_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dep_name',
        ),
    ]
