# Generated by Django 4.2.1 on 2023-06-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_data', '0024_employee_is_active_alter_department_dep_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Department Name'),
        ),
    ]
