# Generated by Django 4.2.1 on 2023-06-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_data', '0027_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female')], default=None, max_length=15, null=True),
        ),
    ]
