# Generated by Django 4.2.1 on 2023-06-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_data', '0028_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(max_length=25, verbose_name='Department Name'),
        ),
    ]
